### ISSUE TITLE
enum34 not working with python3.6 (post7 version)

### ISSUE THREAD

**Issue by shaulimaya** [coralogix/python-coralogix-sdk#5]
Hey!

The reason for it , describes here:
https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag

Can you please fix?

**Comment by EldarAliiev** [comment]
Thanks for report.
We will check and fix it.

**Comment by agmond** [comment]
Was this issue fixed?
For Python >= 3.4 you should drop the package `enum34` and use `enum` from the standard library.

**Comment by EldarAliiev** [comment]
https://github.com/coralogix/python-coralogix-sdk/pull/6

**Comment by EldarAliiev** [comment]
Fixed.

**Comment by agmond** [comment]
Thank you!
